name: neko

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push neko Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker-compose.yml
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/neko:latest

    - name: Verify Image
      run: docker run --rm ghcr.io/${{ github.repository_owner }}/neko:latest uname -m
